### ISSUE TITLE
Base setup

### ISSUE THREAD

**Issue by stefdegroot** [Dartroom/contracts#1]
Create a base setup for the contract interface system.

**Tasks:**
- [x] setup folder structure
- [x] setup base TypeScript interface
- [x] setup test environment in Node.js and browsers
