### ISSUE TITLE
TEAL: Algo fixed bid contract

### ISSUE THREAD

**Issue by stefdegroot** [Dartroom/contracts#2]
Create and test a fully featured TEAL 6 contract of a fixed price listing with prices in Algorand.

**Features:**
- [x] Build with a single stateless contract
- [x] Direct payment from the buyer to shareholders
- [x] configurable payout address
- [x] configurable shares
- [x] Multi-asset buying and listing (more than one token can be bought or listed at once in the same contract)
- [x] Extract tokens function
- [x] Deposit tokens function
- [x] close out as a separate function

**Tasks:**
- [x] create TEAL contract
- [x] test all TEAL routes on Testnet
