### ISSUE TITLE
TEAL: AC fixed bid contract

### ISSUE THREAD

**Issue by stefdegroot** [Dartroom/contracts#3]
Create and test a fully featured TEAL 6 contract of a fixed price listing with prices in any ASA.

**Features:**
- [x] Build with a single stateful contract
- [x] Buyer pays to the contract itself for individual shareholder claims
- [x] claim functions for all shareholders
- [x] configurable payout address
- [x] configurable shares
- [x] Multi-asset buying and listing (more than one token can be bought or listed at once in the same contract)
- [x] Extract tokens function
- [x] Deposit tokens function
- [x] close out as a separate function

**Tasks:**
- [x] create TEAL contract
- [x] test all TEAL routes on Testnet
