### ISSUE TITLE
FixedBid contract events

### ISSUE THREAD

**Issue by stefdegroot** [Dartroom/contracts#34]
Find and return all events around the FixedBid contract. All events are parsed, and the original params are returned alongside the full transaction objects if requested.

**Tasks:**
- [ ] Add new function on the fixed bid provider
- [ ] Fetch all transactions on the `/v2/accounts/:account-id/transactions` indexer endpoint
- [ ] Parse event types:
    - [ ] deploy
    - [ ] setup
    - [ ] deposit
    - [ ] buy
    - [ ] extract
    - [ ] destroy
