### ISSUE TITLE
TEAL contract for auctions priced in Algo

### ISSUE THREAD

**Issue by stefdegroot** [Dartroom/contracts#5]
Create and test a fully featured TEAL 6 contract of an auction with prices in Algo.

**Features:**
- [x] Build with a single stateful contract
- [x] Bidder pays the contract itself
- [x] end auction function that distributes all the funds
- [x] configurable payout address
- [x] configurable shares
- [x] configurable reserve price
- [x] configurable duration
- [x] min bid increase protection (to prevent share division errors)
- [x] snipe protection (min time to counter bid must be 30 min)
- [x] bid increment setting independent of share division protection

**Tasks:**
- [x] create TEAL contract
- [x] test all TEAL routes on Testnet
