### ISSUE TITLE
TEAL: AC reserve auction contract

### ISSUE THREAD

**Issue by stefdegroot** [Dartroom/contracts#6]
Create and test a fully featured TEAL 6 contract of an auction with prices in ASA.

**Features:**
- [ ] Build with a single stateful contract
- [ ] Bidder pays the contract itself for individual shareholder claims
- [ ] backup bid repayment address in case of opt-out of the ASA
- [ ] claim functions for all shareholders
- [ ] configurable payout address
- [ ] configurable shares
- [ ] configurable reserve price
- [ ] configurable duration
- [ ] min bid increase protection (to prevent share division errors)
- [ ] snipe protection (min time to counter bid must be 30 min)
- [ ] close out as a separate function

**Tasks:**
- [ ] create TEAL contract
- [ ] test all TEAL routes on Testnet
